
package archives;

/**
 *
 * @author angel
 */
public class Main extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jd_carreras = new javax.swing.JDialog();
        jPanel_VER_carreras = new javax.swing.JPanel();
        jtp_carreras = new javax.swing.JTabbedPane();
        jPanel_CARRERA_agregar = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        rbt_CARRERA_agregar_activo = new javax.swing.JRadioButton();
        rbt_CARRERA_agregar_inactivo = new javax.swing.JRadioButton();
        tf_CARRERA_agregar_codigo = new javax.swing.JTextField();
        tf_CARRERA_agregar_nombre = new javax.swing.JTextField();
        bt_CARRERA_agregar_add = new javax.swing.JButton();
        jLabel37 = new javax.swing.JLabel();
        jPanel_CARRERA_ver = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jtbl_CARRERA_listar = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        jPanel_CARRERA_buscar = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        jtbl_CARRERA_buscar = new javax.swing.JTable();
        bt_CARRERA_buscar = new javax.swing.JButton();
        tf_CARRERA_buscar = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jd_investigadores = new javax.swing.JDialog();
        jPanel_VER_investigadores = new javax.swing.JPanel();
        jtp_VER_investigadores = new javax.swing.JTabbedPane();
        jPanel_INVT_add = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        tf_VER_INV_agregar_codigo = new javax.swing.JTextField();
        tf_VER_INV_agregar_nombre = new javax.swing.JTextField();
        jcb_VER_INV_agregar_carrera = new javax.swing.JComboBox<>();
        rbt_VER_INV_agregar_activo = new javax.swing.JRadioButton();
        rbt_VER_INV_agregar_inactivo = new javax.swing.JRadioButton();
        bt_VER_INV_agregar_add = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jPanel_INVT_view = new javax.swing.JPanel();
        jScrollPane11 = new javax.swing.JScrollPane();
        jtbl_INVT_listar = new javax.swing.JTable();
        jPanel_INVT_delete = new javax.swing.JPanel();
        jScrollPane8 = new javax.swing.JScrollPane();
        jtbl_INVT_borrar = new javax.swing.JTable();
        bt_INV_buscar = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jd_proyectos = new javax.swing.JDialog();
        jPanel_VER_proyectos = new javax.swing.JPanel();
        jtp_VER_proyectos = new javax.swing.JTabbedPane();
        jPanel_VER_PROY_add = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        rbt_VER_PROY_agregar_iniciado = new javax.swing.JRadioButton();
        rbt_VER_PROY_agregar_enviado = new javax.swing.JRadioButton();
        rbt_VER_PROY_agregar_publicado = new javax.swing.JRadioButton();
        rbt_VER_PROY_agregar_rechazado = new javax.swing.JRadioButton();
        tf_VER_PROY_agregar_codigo = new javax.swing.JTextField();
        tf_VER_PROY_agregar_tema = new javax.swing.JTextField();
        jcb_VER_PROY_agregar_carrera = new javax.swing.JComboBox<>();
        bt_VER_PROY_agregar_add = new javax.swing.JButton();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jPanel_VER_PROY_view = new javax.swing.JPanel();
        jScrollPane13 = new javax.swing.JScrollPane();
        jtbl_PROY_ver = new javax.swing.JTable();
        jPanel_VER_PROY_delete = new javax.swing.JPanel();
        jScrollPane10 = new javax.swing.JScrollPane();
        jtbl_PROY_buscar = new javax.swing.JTable();
        bt_PROY_buscar = new javax.swing.JButton();
        jTextField5 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jd_publicaciones = new javax.swing.JDialog();
        jPanel_VER_publicaciones = new javax.swing.JPanel();
        jtp_publicaciones = new javax.swing.JTabbedPane();
        jPanel_VER_PUB_add = new javax.swing.JPanel();
        jPanel17 = new javax.swing.JPanel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        tf_VER_PUB_agregar_codigo = new javax.swing.JTextField();
        jcb_VER_PUB_agregar_proyecto = new javax.swing.JComboBox<>();
        rbt_VER_PUB_agregar_publicacion = new javax.swing.JRadioButton();
        rbt_VER_PUB_agregar_revista = new javax.swing.JRadioButton();
        bt_VER_PUB_agregar_add = new javax.swing.JButton();
        jTextField7 = new javax.swing.JTextField();
        jPanel_VER_PUB_view = new javax.swing.JPanel();
        jScrollPane16 = new javax.swing.JScrollPane();
        jtbl_PUB_listar = new javax.swing.JTable();
        jPanel_VER_PUB_delete = new javax.swing.JPanel();
        jScrollPane15 = new javax.swing.JScrollPane();
        jtbl_PUB_buscar = new javax.swing.JTable();
        bt_VER_PUB_borrar_delete = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        btg_VER_CARR_agregar_estado = new javax.swing.ButtonGroup();
        btg_VER_INV_agregar_estado = new javax.swing.ButtonGroup();
        btg_VER_PROY_agregar_estado = new javax.swing.ButtonGroup();
        btg_VER_PUB_agregar_estado = new javax.swing.ButtonGroup();
        bt_carreras = new javax.swing.JButton();
        bt_proyectos = new javax.swing.JButton();
        bt_investigadores = new javax.swing.JButton();
        bt_publicaciones = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jm_FILE = new javax.swing.JMenu();
        jmi_FILE_abrir = new javax.swing.JMenuItem();
        jmi_FILE_guardar = new javax.swing.JMenuItem();
        jmi_FILE_close = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jmi_FILE_exit = new javax.swing.JMenuItem();
        jm_VER = new javax.swing.JMenu();
        jmi_VER_carreras = new javax.swing.JMenuItem();
        jmi_VER_investigadores = new javax.swing.JMenuItem();
        jmi_VER_proyectos = new javax.swing.JMenuItem();
        jmi_VER_publicaciones = new javax.swing.JMenuItem();

        jd_carreras.setTitle("Carreras");

        jtp_carreras.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jtp_carrerasStateChanged(evt);
            }
        });

        jLabel1.setText("Código:");

        jLabel2.setText("Nombre:");

        jLabel3.setText("Estado:");

        btg_VER_CARR_agregar_estado.add(rbt_CARRERA_agregar_activo);
        rbt_CARRERA_agregar_activo.setText("Activo");

        btg_VER_CARR_agregar_estado.add(rbt_CARRERA_agregar_inactivo);
        rbt_CARRERA_agregar_inactivo.setSelected(true);
        rbt_CARRERA_agregar_inactivo.setText("Inactivo");

        bt_CARRERA_agregar_add.setText("Agregar");
        bt_CARRERA_agregar_add.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_CARRERA_agregar_addMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(bt_CARRERA_agregar_add)
                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel6Layout.createSequentialGroup()
                            .addComponent(jLabel2)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(tf_CARRERA_agregar_nombre))
                        .addGroup(jPanel6Layout.createSequentialGroup()
                            .addComponent(jLabel1)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(tf_CARRERA_agregar_codigo, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel6Layout.createSequentialGroup()
                            .addComponent(jLabel3)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(rbt_CARRERA_agregar_inactivo)
                                .addComponent(rbt_CARRERA_agregar_activo)))))
                .addContainerGap(15, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(tf_CARRERA_agregar_codigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(tf_CARRERA_agregar_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(rbt_CARRERA_agregar_activo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rbt_CARRERA_agregar_inactivo)
                .addGap(18, 18, 18)
                .addComponent(bt_CARRERA_agregar_add)
                .addContainerGap(106, Short.MAX_VALUE))
        );

        jLabel37.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jLabel37.setText("Agregar una carrera");

        javax.swing.GroupLayout jPanel_CARRERA_agregarLayout = new javax.swing.GroupLayout(jPanel_CARRERA_agregar);
        jPanel_CARRERA_agregar.setLayout(jPanel_CARRERA_agregarLayout);
        jPanel_CARRERA_agregarLayout.setHorizontalGroup(
            jPanel_CARRERA_agregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_CARRERA_agregarLayout.createSequentialGroup()
                .addGap(116, 116, 116)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(122, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_CARRERA_agregarLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel37)
                .addGap(199, 199, 199))
        );
        jPanel_CARRERA_agregarLayout.setVerticalGroup(
            jPanel_CARRERA_agregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_CARRERA_agregarLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel37)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(50, Short.MAX_VALUE))
        );

        jtp_carreras.addTab("Agregar", jPanel_CARRERA_agregar);

        jtbl_CARRERA_listar.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Código", "Nombre", "Estado"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane4.setViewportView(jtbl_CARRERA_listar);

        jLabel6.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jLabel6.setText("Listado de Carreras");

        javax.swing.GroupLayout jPanel_CARRERA_verLayout = new javax.swing.GroupLayout(jPanel_CARRERA_ver);
        jPanel_CARRERA_ver.setLayout(jPanel_CARRERA_verLayout);
        jPanel_CARRERA_verLayout.setHorizontalGroup(
            jPanel_CARRERA_verLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_CARRERA_verLayout.createSequentialGroup()
                .addContainerGap(31, Short.MAX_VALUE)
                .addGroup(jPanel_CARRERA_verLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_CARRERA_verLayout.createSequentialGroup()
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 490, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_CARRERA_verLayout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(200, 200, 200))))
        );
        jPanel_CARRERA_verLayout.setVerticalGroup(
            jPanel_CARRERA_verLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_CARRERA_verLayout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28))
        );

        jtp_carreras.addTab("Ver", jPanel_CARRERA_ver);

        jtbl_CARRERA_buscar.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Código", "Nombre", "Estado"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane5.setViewportView(jtbl_CARRERA_buscar);

        bt_CARRERA_buscar.setText("Buscar");

        jLabel4.setText("Código de Carrera:");

        jLabel5.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jLabel5.setText("Búsqueda de Carrera por # de código");

        javax.swing.GroupLayout jPanel_CARRERA_buscarLayout = new javax.swing.GroupLayout(jPanel_CARRERA_buscar);
        jPanel_CARRERA_buscar.setLayout(jPanel_CARRERA_buscarLayout);
        jPanel_CARRERA_buscarLayout.setHorizontalGroup(
            jPanel_CARRERA_buscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_CARRERA_buscarLayout.createSequentialGroup()
                .addGroup(jPanel_CARRERA_buscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_CARRERA_buscarLayout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addGroup(jPanel_CARRERA_buscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel_CARRERA_buscarLayout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tf_CARRERA_buscar, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(bt_CARRERA_buscar))
                            .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel_CARRERA_buscarLayout.createSequentialGroup()
                        .addGap(131, 131, 131)
                        .addComponent(jLabel5)))
                .addContainerGap(44, Short.MAX_VALUE))
        );
        jPanel_CARRERA_buscarLayout.setVerticalGroup(
            jPanel_CARRERA_buscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_CARRERA_buscarLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel_CARRERA_buscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bt_CARRERA_buscar)
                    .addComponent(tf_CARRERA_buscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34))
        );

        jtp_carreras.addTab("Buscar", jPanel_CARRERA_buscar);

        javax.swing.GroupLayout jPanel_VER_carrerasLayout = new javax.swing.GroupLayout(jPanel_VER_carreras);
        jPanel_VER_carreras.setLayout(jPanel_VER_carrerasLayout);
        jPanel_VER_carrerasLayout.setHorizontalGroup(
            jPanel_VER_carrerasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_VER_carrerasLayout.createSequentialGroup()
                .addComponent(jtp_carreras, javax.swing.GroupLayout.PREFERRED_SIZE, 562, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel_VER_carrerasLayout.setVerticalGroup(
            jPanel_VER_carrerasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_VER_carrerasLayout.createSequentialGroup()
                .addComponent(jtp_carreras, javax.swing.GroupLayout.PREFERRED_SIZE, 433, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jd_carrerasLayout = new javax.swing.GroupLayout(jd_carreras.getContentPane());
        jd_carreras.getContentPane().setLayout(jd_carrerasLayout);
        jd_carrerasLayout.setHorizontalGroup(
            jd_carrerasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel_VER_carreras, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jd_carrerasLayout.setVerticalGroup(
            jd_carrerasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel_VER_carreras, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jd_investigadores.setTitle("Investigadores");

        jLabel7.setText("Código:");

        jLabel8.setText("Nombre:");

        jLabel9.setText("Fecha de Ingreso:");

        jLabel10.setText("Carrera");

        jLabel11.setText("Estado:");

        jcb_VER_INV_agregar_carrera.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar..." }));

        btg_VER_INV_agregar_estado.add(rbt_VER_INV_agregar_activo);
        rbt_VER_INV_agregar_activo.setText("Activo");

        btg_VER_INV_agregar_estado.add(rbt_VER_INV_agregar_inactivo);
        rbt_VER_INV_agregar_inactivo.setSelected(true);
        rbt_VER_INV_agregar_inactivo.setText("Inactivo");

        bt_VER_INV_agregar_add.setText("Agregar");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addGap(18, 18, 18)
                        .addComponent(rbt_VER_INV_agregar_activo)
                        .addGap(18, 18, 18)
                        .addComponent(rbt_VER_INV_agregar_inactivo))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(bt_VER_INV_agregar_add)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addGap(18, 18, 18)
                                .addComponent(tf_VER_INV_agregar_nombre))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addGap(18, 18, 18)
                                .addComponent(tf_VER_INV_agregar_codigo, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField1))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addGap(18, 18, 18)
                                .addComponent(jcb_VER_INV_agregar_carrera, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(39, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(tf_VER_INV_agregar_codigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(tf_VER_INV_agregar_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(34, 34, 34))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jcb_VER_INV_agregar_carrera, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel10)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(rbt_VER_INV_agregar_activo)
                    .addComponent(rbt_VER_INV_agregar_inactivo))
                .addGap(18, 18, 18)
                .addComponent(bt_VER_INV_agregar_add)
                .addContainerGap(48, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel_INVT_addLayout = new javax.swing.GroupLayout(jPanel_INVT_add);
        jPanel_INVT_add.setLayout(jPanel_INVT_addLayout);
        jPanel_INVT_addLayout.setHorizontalGroup(
            jPanel_INVT_addLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_INVT_addLayout.createSequentialGroup()
                .addGap(146, 146, 146)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(146, Short.MAX_VALUE))
        );
        jPanel_INVT_addLayout.setVerticalGroup(
            jPanel_INVT_addLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_INVT_addLayout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(85, Short.MAX_VALUE))
        );

        jtp_VER_investigadores.addTab("Agregar", jPanel_INVT_add);

        jtbl_INVT_listar.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre", "Codigo Inv.", "Codigo Carrera.", "Estado", "Fecha Ingreso"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane11.setViewportView(jtbl_INVT_listar);

        javax.swing.GroupLayout jPanel_INVT_viewLayout = new javax.swing.GroupLayout(jPanel_INVT_view);
        jPanel_INVT_view.setLayout(jPanel_INVT_viewLayout);
        jPanel_INVT_viewLayout.setHorizontalGroup(
            jPanel_INVT_viewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 672, Short.MAX_VALUE)
            .addGroup(jPanel_INVT_viewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel_INVT_viewLayout.createSequentialGroup()
                    .addGap(109, 109, 109)
                    .addComponent(jScrollPane11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(109, Short.MAX_VALUE)))
        );
        jPanel_INVT_viewLayout.setVerticalGroup(
            jPanel_INVT_viewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 426, Short.MAX_VALUE)
            .addGroup(jPanel_INVT_viewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel_INVT_viewLayout.createSequentialGroup()
                    .addGap(44, 44, 44)
                    .addComponent(jScrollPane11, javax.swing.GroupLayout.PREFERRED_SIZE, 338, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(44, Short.MAX_VALUE)))
        );

        jtp_VER_investigadores.addTab("Listar", jPanel_INVT_view);

        jtbl_INVT_borrar.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre", "Codigo Inv.", "Codigo Carrera.", "Estado", "Fecha Ingreso"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane8.setViewportView(jtbl_INVT_borrar);

        bt_INV_buscar.setText("Buscar");

        jLabel12.setText("Buscar");

        javax.swing.GroupLayout jPanel_INVT_deleteLayout = new javax.swing.GroupLayout(jPanel_INVT_delete);
        jPanel_INVT_delete.setLayout(jPanel_INVT_deleteLayout);
        jPanel_INVT_deleteLayout.setHorizontalGroup(
            jPanel_INVT_deleteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_INVT_deleteLayout.createSequentialGroup()
                .addGroup(jPanel_INVT_deleteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_INVT_deleteLayout.createSequentialGroup()
                        .addGap(191, 191, 191)
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bt_INV_buscar))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_INVT_deleteLayout.createSequentialGroup()
                        .addGap(101, 101, 101)
                        .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(117, Short.MAX_VALUE))
        );
        jPanel_INVT_deleteLayout.setVerticalGroup(
            jPanel_INVT_deleteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_INVT_deleteLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 338, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel_INVT_deleteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bt_INV_buscar)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        jtp_VER_investigadores.addTab("Buscar", jPanel_INVT_delete);

        javax.swing.GroupLayout jPanel_VER_investigadoresLayout = new javax.swing.GroupLayout(jPanel_VER_investigadores);
        jPanel_VER_investigadores.setLayout(jPanel_VER_investigadoresLayout);
        jPanel_VER_investigadoresLayout.setHorizontalGroup(
            jPanel_VER_investigadoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jtp_VER_investigadores)
        );
        jPanel_VER_investigadoresLayout.setVerticalGroup(
            jPanel_VER_investigadoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jtp_VER_investigadores)
        );

        javax.swing.GroupLayout jd_investigadoresLayout = new javax.swing.GroupLayout(jd_investigadores.getContentPane());
        jd_investigadores.getContentPane().setLayout(jd_investigadoresLayout);
        jd_investigadoresLayout.setHorizontalGroup(
            jd_investigadoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel_VER_investigadores, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jd_investigadoresLayout.setVerticalGroup(
            jd_investigadoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel_VER_investigadores, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jd_proyectos.setTitle("Proyectos");

        jLabel17.setText("Código:");

        jLabel18.setText("Tema:");

        jLabel19.setText("Investigador:");

        jLabel20.setText("Fecha Inicio:");

        jLabel21.setText("Fecha Fin:");

        jLabel22.setText("Estado:");

        btg_VER_PROY_agregar_estado.add(rbt_VER_PROY_agregar_iniciado);
        rbt_VER_PROY_agregar_iniciado.setText("Iniciado");

        btg_VER_PROY_agregar_estado.add(rbt_VER_PROY_agregar_enviado);
        rbt_VER_PROY_agregar_enviado.setText("Enviado");

        btg_VER_PROY_agregar_estado.add(rbt_VER_PROY_agregar_publicado);
        rbt_VER_PROY_agregar_publicado.setText("Publicado");

        btg_VER_PROY_agregar_estado.add(rbt_VER_PROY_agregar_rechazado);
        rbt_VER_PROY_agregar_rechazado.setText("Rechazado");

        jcb_VER_PROY_agregar_carrera.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione un investigador..." }));

        bt_VER_PROY_agregar_add.setText("Agregar");

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel22)
                    .addComponent(jLabel21)
                    .addComponent(jLabel20)
                    .addComponent(jLabel17)
                    .addComponent(jLabel18)
                    .addComponent(jLabel19))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(bt_VER_PROY_agregar_add)
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel10Layout.createSequentialGroup()
                                .addComponent(rbt_VER_PROY_agregar_publicado)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(rbt_VER_PROY_agregar_rechazado))
                            .addGroup(jPanel10Layout.createSequentialGroup()
                                .addComponent(rbt_VER_PROY_agregar_iniciado)
                                .addGap(18, 18, 18)
                                .addComponent(rbt_VER_PROY_agregar_enviado))
                            .addComponent(tf_VER_PROY_agregar_codigo)
                            .addComponent(tf_VER_PROY_agregar_tema, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)))
                    .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jTextField4, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jTextField3, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jcb_VER_PROY_agregar_carrera, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(tf_VER_PROY_agregar_codigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(tf_VER_PROY_agregar_tema, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(jcb_VER_PROY_agregar_carrera, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel22)
                    .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(rbt_VER_PROY_agregar_iniciado)
                        .addComponent(rbt_VER_PROY_agregar_enviado)))
                .addGap(18, 18, 18)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbt_VER_PROY_agregar_publicado)
                    .addComponent(rbt_VER_PROY_agregar_rechazado))
                .addGap(18, 18, 18)
                .addComponent(bt_VER_PROY_agregar_add)
                .addContainerGap(32, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel_VER_PROY_addLayout = new javax.swing.GroupLayout(jPanel_VER_PROY_add);
        jPanel_VER_PROY_add.setLayout(jPanel_VER_PROY_addLayout);
        jPanel_VER_PROY_addLayout.setHorizontalGroup(
            jPanel_VER_PROY_addLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_VER_PROY_addLayout.createSequentialGroup()
                .addContainerGap(159, Short.MAX_VALUE)
                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(138, 138, 138))
        );
        jPanel_VER_PROY_addLayout.setVerticalGroup(
            jPanel_VER_PROY_addLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_VER_PROY_addLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(28, Short.MAX_VALUE))
        );

        jtp_VER_proyectos.addTab("Agregar", jPanel_VER_PROY_add);

        jtbl_PROY_ver.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código Proyecto", "Nombre - Tema", "Fecha Inicio", "Fecha Fin", "Codigo Investigador", "Estado"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane13.setViewportView(jtbl_PROY_ver);

        javax.swing.GroupLayout jPanel_VER_PROY_viewLayout = new javax.swing.GroupLayout(jPanel_VER_PROY_view);
        jPanel_VER_PROY_view.setLayout(jPanel_VER_PROY_viewLayout);
        jPanel_VER_PROY_viewLayout.setHorizontalGroup(
            jPanel_VER_PROY_viewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_VER_PROY_viewLayout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(jScrollPane13, javax.swing.GroupLayout.PREFERRED_SIZE, 647, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(42, Short.MAX_VALUE))
        );
        jPanel_VER_PROY_viewLayout.setVerticalGroup(
            jPanel_VER_PROY_viewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_VER_PROY_viewLayout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(jScrollPane13, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(51, Short.MAX_VALUE))
        );

        jtp_VER_proyectos.addTab("Listar", jPanel_VER_PROY_view);

        jtbl_PROY_buscar.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código Proyecto", "Nombre - Tema", "Fecha Inicio", "Fecha Fin", "Codigo Investigador", "Estado"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane10.setViewportView(jtbl_PROY_buscar);

        bt_PROY_buscar.setText("Buscar");

        jLabel13.setText("Código de Proyecto");

        javax.swing.GroupLayout jPanel_VER_PROY_deleteLayout = new javax.swing.GroupLayout(jPanel_VER_PROY_delete);
        jPanel_VER_PROY_delete.setLayout(jPanel_VER_PROY_deleteLayout);
        jPanel_VER_PROY_deleteLayout.setHorizontalGroup(
            jPanel_VER_PROY_deleteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_VER_PROY_deleteLayout.createSequentialGroup()
                .addGap(133, 133, 133)
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(bt_PROY_buscar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_VER_PROY_deleteLayout.createSequentialGroup()
                .addContainerGap(38, Short.MAX_VALUE)
                .addComponent(jScrollPane10, javax.swing.GroupLayout.PREFERRED_SIZE, 647, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(45, Short.MAX_VALUE))
        );
        jPanel_VER_PROY_deleteLayout.setVerticalGroup(
            jPanel_VER_PROY_deleteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_VER_PROY_deleteLayout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(jScrollPane10, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel_VER_PROY_deleteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bt_PROY_buscar)
                    .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        jtp_VER_proyectos.addTab("Buscar", jPanel_VER_PROY_delete);

        javax.swing.GroupLayout jPanel_VER_proyectosLayout = new javax.swing.GroupLayout(jPanel_VER_proyectos);
        jPanel_VER_proyectos.setLayout(jPanel_VER_proyectosLayout);
        jPanel_VER_proyectosLayout.setHorizontalGroup(
            jPanel_VER_proyectosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jtp_VER_proyectos)
        );
        jPanel_VER_proyectosLayout.setVerticalGroup(
            jPanel_VER_proyectosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_VER_proyectosLayout.createSequentialGroup()
                .addComponent(jtp_VER_proyectos)
                .addContainerGap())
        );

        javax.swing.GroupLayout jd_proyectosLayout = new javax.swing.GroupLayout(jd_proyectos.getContentPane());
        jd_proyectos.getContentPane().setLayout(jd_proyectosLayout);
        jd_proyectosLayout.setHorizontalGroup(
            jd_proyectosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel_VER_proyectos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jd_proyectosLayout.setVerticalGroup(
            jd_proyectosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel_VER_proyectos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jd_publicaciones.setTitle("Publicaciones");

        jLabel29.setText("Código:");

        jLabel30.setText("Proyecto:");

        jLabel31.setText("Fecha:");

        jLabel32.setText("Tipo:");

        jcb_VER_PUB_agregar_proyecto.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        btg_VER_PUB_agregar_estado.add(rbt_VER_PUB_agregar_publicacion);
        rbt_VER_PUB_agregar_publicacion.setText("Publicación");

        btg_VER_PUB_agregar_estado.add(rbt_VER_PUB_agregar_revista);
        rbt_VER_PUB_agregar_revista.setText("Revista");

        bt_VER_PUB_agregar_add.setText("Guardar");

        javax.swing.GroupLayout jPanel17Layout = new javax.swing.GroupLayout(jPanel17);
        jPanel17.setLayout(jPanel17Layout);
        jPanel17Layout.setHorizontalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel17Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(bt_VER_PUB_agregar_add)
                    .addGroup(jPanel17Layout.createSequentialGroup()
                        .addGroup(jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel32, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel31, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel30, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel29, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tf_VER_PUB_agregar_codigo, javax.swing.GroupLayout.DEFAULT_SIZE, 230, Short.MAX_VALUE)
                            .addComponent(jcb_VER_PUB_agregar_proyecto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel17Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addGroup(jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(rbt_VER_PUB_agregar_revista)
                                    .addComponent(rbt_VER_PUB_agregar_publicacion)))
                            .addComponent(jTextField7))))
                .addContainerGap(17, Short.MAX_VALUE))
        );
        jPanel17Layout.setVerticalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel17Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel29)
                    .addComponent(tf_VER_PUB_agregar_codigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel30)
                    .addComponent(jcb_VER_PUB_agregar_proyecto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel31)
                    .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel32)
                    .addComponent(rbt_VER_PUB_agregar_publicacion))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rbt_VER_PUB_agregar_revista)
                .addGap(18, 18, 18)
                .addComponent(bt_VER_PUB_agregar_add)
                .addContainerGap(11, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel_VER_PUB_addLayout = new javax.swing.GroupLayout(jPanel_VER_PUB_add);
        jPanel_VER_PUB_add.setLayout(jPanel_VER_PUB_addLayout);
        jPanel_VER_PUB_addLayout.setHorizontalGroup(
            jPanel_VER_PUB_addLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_VER_PUB_addLayout.createSequentialGroup()
                .addGap(191, 191, 191)
                .addComponent(jPanel17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(196, Short.MAX_VALUE))
        );
        jPanel_VER_PUB_addLayout.setVerticalGroup(
            jPanel_VER_PUB_addLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_VER_PUB_addLayout.createSequentialGroup()
                .addGap(79, 79, 79)
                .addComponent(jPanel17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(96, Short.MAX_VALUE))
        );

        jtp_publicaciones.addTab("Agregar", jPanel_VER_PUB_add);

        jtbl_PUB_listar.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código Publicación", "Código Proyecto", "Fecha Publicación", "Revista o Conferencia"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane16.setViewportView(jtbl_PUB_listar);

        javax.swing.GroupLayout jPanel_VER_PUB_viewLayout = new javax.swing.GroupLayout(jPanel_VER_PUB_view);
        jPanel_VER_PUB_view.setLayout(jPanel_VER_PUB_viewLayout);
        jPanel_VER_PUB_viewLayout.setHorizontalGroup(
            jPanel_VER_PUB_viewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_VER_PUB_viewLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jScrollPane16, javax.swing.GroupLayout.PREFERRED_SIZE, 659, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(32, Short.MAX_VALUE))
        );
        jPanel_VER_PUB_viewLayout.setVerticalGroup(
            jPanel_VER_PUB_viewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_VER_PUB_viewLayout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(jScrollPane16, javax.swing.GroupLayout.PREFERRED_SIZE, 344, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(48, Short.MAX_VALUE))
        );

        jtp_publicaciones.addTab("Listar", jPanel_VER_PUB_view);

        jtbl_PUB_buscar.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código Publicación", "Código Proyecto", "Fecha Publicación", "Revista o Conferencia"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane15.setViewportView(jtbl_PUB_buscar);

        bt_VER_PUB_borrar_delete.setText("Buscar");

        jLabel14.setText("Buscar Publicación:");

        javax.swing.GroupLayout jPanel_VER_PUB_deleteLayout = new javax.swing.GroupLayout(jPanel_VER_PUB_delete);
        jPanel_VER_PUB_delete.setLayout(jPanel_VER_PUB_deleteLayout);
        jPanel_VER_PUB_deleteLayout.setHorizontalGroup(
            jPanel_VER_PUB_deleteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_VER_PUB_deleteLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jScrollPane15, javax.swing.GroupLayout.PREFERRED_SIZE, 659, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(25, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_VER_PUB_deleteLayout.createSequentialGroup()
                .addGap(163, 163, 163)
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bt_VER_PUB_borrar_delete)
                .addGap(51, 51, 51))
        );
        jPanel_VER_PUB_deleteLayout.setVerticalGroup(
            jPanel_VER_PUB_deleteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_VER_PUB_deleteLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jScrollPane15, javax.swing.GroupLayout.PREFERRED_SIZE, 344, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel_VER_PUB_deleteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bt_VER_PUB_borrar_delete)
                    .addComponent(jLabel14)
                    .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        jtp_publicaciones.addTab("Buscar", jPanel_VER_PUB_delete);

        javax.swing.GroupLayout jPanel_VER_publicacionesLayout = new javax.swing.GroupLayout(jPanel_VER_publicaciones);
        jPanel_VER_publicaciones.setLayout(jPanel_VER_publicacionesLayout);
        jPanel_VER_publicacionesLayout.setHorizontalGroup(
            jPanel_VER_publicacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jtp_publicaciones)
        );
        jPanel_VER_publicacionesLayout.setVerticalGroup(
            jPanel_VER_publicacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jtp_publicaciones)
        );

        javax.swing.GroupLayout jd_publicacionesLayout = new javax.swing.GroupLayout(jd_publicaciones.getContentPane());
        jd_publicaciones.getContentPane().setLayout(jd_publicacionesLayout);
        jd_publicacionesLayout.setHorizontalGroup(
            jd_publicacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel_VER_publicaciones, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jd_publicacionesLayout.setVerticalGroup(
            jd_publicacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel_VER_publicaciones, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Base Datos de Investigadores");

        bt_carreras.setText("Carreras");
        bt_carreras.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_carrerasMouseClicked(evt);
            }
        });

        bt_proyectos.setText("Proyectos");
        bt_proyectos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_proyectosMouseClicked(evt);
            }
        });

        bt_investigadores.setText("Investigadores");
        bt_investigadores.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_investigadoresMouseClicked(evt);
            }
        });

        bt_publicaciones.setText("Publicaciones");
        bt_publicaciones.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_publicacionesMouseClicked(evt);
            }
        });

        jm_FILE.setText("File");

        jmi_FILE_abrir.setText("Abrir");
        jm_FILE.add(jmi_FILE_abrir);

        jmi_FILE_guardar.setText("Guardar");
        jm_FILE.add(jmi_FILE_guardar);

        jmi_FILE_close.setText("Close");
        jm_FILE.add(jmi_FILE_close);
        jm_FILE.add(jSeparator1);

        jmi_FILE_exit.setText("Exit");
        jm_FILE.add(jmi_FILE_exit);

        jMenuBar1.add(jm_FILE);

        jm_VER.setText("Ver");

        jmi_VER_carreras.setText("Carreras");
        jmi_VER_carreras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmi_VER_carrerasActionPerformed(evt);
            }
        });
        jm_VER.add(jmi_VER_carreras);

        jmi_VER_investigadores.setText("Investigadores");
        jmi_VER_investigadores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmi_VER_investigadoresActionPerformed(evt);
            }
        });
        jm_VER.add(jmi_VER_investigadores);

        jmi_VER_proyectos.setText("Proyectos");
        jmi_VER_proyectos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmi_VER_proyectosActionPerformed(evt);
            }
        });
        jm_VER.add(jmi_VER_proyectos);

        jmi_VER_publicaciones.setText("Publicaciones");
        jmi_VER_publicaciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmi_VER_publicacionesActionPerformed(evt);
            }
        });
        jm_VER.add(jmi_VER_publicaciones);

        jMenuBar1.add(jm_VER);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(210, 210, 210)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bt_publicaciones)
                    .addComponent(bt_carreras)
                    .addComponent(bt_investigadores)
                    .addComponent(bt_proyectos))
                .addContainerGap(327, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(105, 105, 105)
                .addComponent(bt_carreras)
                .addGap(18, 18, 18)
                .addComponent(bt_investigadores)
                .addGap(18, 18, 18)
                .addComponent(bt_proyectos)
                .addGap(18, 18, 18)
                .addComponent(bt_publicaciones)
                .addContainerGap(156, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //acción de menú en menú principal para abrir dialog de PROYECTOS
    private void jmi_VER_proyectosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmi_VER_proyectosActionPerformed
        jd_proyectos.pack();
        jd_proyectos.setModal(true);
        jd_proyectos.setLocationRelativeTo(this);
        jd_proyectos.setVisible(true);
    }//GEN-LAST:event_jmi_VER_proyectosActionPerformed

    //acción de menú en menú principal para abrir dialog de PUBLICACIONES
    private void jmi_VER_publicacionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmi_VER_publicacionesActionPerformed
        jd_publicaciones.pack();
        jd_publicaciones.setModal(true);
        jd_publicaciones.setLocationRelativeTo(this);
        jd_publicaciones.setVisible(true);
    }//GEN-LAST:event_jmi_VER_publicacionesActionPerformed

    //acción de menú en menú principal para abrir dialog de CARRERAS
    private void jmi_VER_carrerasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmi_VER_carrerasActionPerformed
        jd_carreras.pack();
        jd_carreras.setModal(true);
        jd_carreras.setLocationRelativeTo(this);
        jd_carreras.setVisible(true);
    }//GEN-LAST:event_jmi_VER_carrerasActionPerformed

    //acción de menú en menú principal para abrir dialog de INVESTIGADORES
    private void jmi_VER_investigadoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmi_VER_investigadoresActionPerformed
        jd_investigadores.pack();
        jd_investigadores.setModal(true);
        jd_investigadores.setLocationRelativeTo(this);
        jd_investigadores.setVisible(true);
    }//GEN-LAST:event_jmi_VER_investigadoresActionPerformed

    //acción de botón en ventana principal para abrir dialog de CARRERAS
    private void bt_carrerasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_carrerasMouseClicked
        jd_carreras.pack();
        jd_carreras.setModal(true);
        jd_carreras.setLocationRelativeTo(this);
        jd_carreras.setVisible(true);
    }//GEN-LAST:event_bt_carrerasMouseClicked

    //acción de botón en ventana principal para abrir dialog de INVESTIGADORES
    private void bt_investigadoresMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_investigadoresMouseClicked
        jd_investigadores.pack();
        jd_investigadores.setModal(true);
        jd_investigadores.setLocationRelativeTo(this);
        jd_investigadores.setVisible(true);
    }//GEN-LAST:event_bt_investigadoresMouseClicked

    //acción de botón en ventana principal para abrir dialog de PROYECTOS
    private void bt_proyectosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_proyectosMouseClicked
        jd_proyectos.pack();
        jd_proyectos.setModal(true);
        jd_proyectos.setLocationRelativeTo(this);
        jd_proyectos.setVisible(true);
    }//GEN-LAST:event_bt_proyectosMouseClicked

    //acción de botón en ventana principal para abrir dialog de PUBLICACIONES
    private void bt_publicacionesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_publicacionesMouseClicked
        jd_publicaciones.pack();
        jd_publicaciones.setModal(true);
        jd_publicaciones.setLocationRelativeTo(this);
        jd_publicaciones.setVisible(true);
    }//GEN-LAST:event_bt_publicacionesMouseClicked

    private void jtp_carrerasStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jtp_carrerasStateChanged
        if(jtp_carreras.getSelectedIndex() ==1){
            //adminPersona ap=new adminPersona(("./amigos.cbm"));
            //ap.cargarArchivo();
            //DefaultComboBoxModel modelo = new DefaultComboBoxModel(ap.getListaPersonas().toArray());
            //cb_amigos.setModel(modelo);
        }
    }//GEN-LAST:event_jtp_carrerasStateChanged

    private void bt_CARRERA_agregar_addMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_CARRERA_agregar_addMouseClicked
        String estado = "";
        
        Carrera carr = new Carrera(Integer.parseInt(tf_CARRERA_agregar_codigo.getText()), tf_CARRERA_agregar_nombre.getText(), estado);
        
        
        AdminArchivo ar = new AdminArchivo("carreras.atc");
    }//GEN-LAST:event_bt_CARRERA_agregar_addMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_CARRERA_agregar_add;
    private javax.swing.JButton bt_CARRERA_buscar;
    private javax.swing.JButton bt_INV_buscar;
    private javax.swing.JButton bt_PROY_buscar;
    private javax.swing.JButton bt_VER_INV_agregar_add;
    private javax.swing.JButton bt_VER_PROY_agregar_add;
    private javax.swing.JButton bt_VER_PUB_agregar_add;
    private javax.swing.JButton bt_VER_PUB_borrar_delete;
    private javax.swing.JButton bt_carreras;
    private javax.swing.JButton bt_investigadores;
    private javax.swing.JButton bt_proyectos;
    private javax.swing.JButton bt_publicaciones;
    private javax.swing.ButtonGroup btg_VER_CARR_agregar_estado;
    private javax.swing.ButtonGroup btg_VER_INV_agregar_estado;
    private javax.swing.ButtonGroup btg_VER_PROY_agregar_estado;
    private javax.swing.ButtonGroup btg_VER_PUB_agregar_estado;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel_CARRERA_agregar;
    private javax.swing.JPanel jPanel_CARRERA_buscar;
    private javax.swing.JPanel jPanel_CARRERA_ver;
    private javax.swing.JPanel jPanel_INVT_add;
    private javax.swing.JPanel jPanel_INVT_delete;
    private javax.swing.JPanel jPanel_INVT_view;
    private javax.swing.JPanel jPanel_VER_PROY_add;
    private javax.swing.JPanel jPanel_VER_PROY_delete;
    private javax.swing.JPanel jPanel_VER_PROY_view;
    private javax.swing.JPanel jPanel_VER_PUB_add;
    private javax.swing.JPanel jPanel_VER_PUB_delete;
    private javax.swing.JPanel jPanel_VER_PUB_view;
    private javax.swing.JPanel jPanel_VER_carreras;
    private javax.swing.JPanel jPanel_VER_investigadores;
    private javax.swing.JPanel jPanel_VER_proyectos;
    private javax.swing.JPanel jPanel_VER_publicaciones;
    private javax.swing.JScrollPane jScrollPane10;
    private javax.swing.JScrollPane jScrollPane11;
    private javax.swing.JScrollPane jScrollPane13;
    private javax.swing.JScrollPane jScrollPane15;
    private javax.swing.JScrollPane jScrollPane16;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JComboBox<String> jcb_VER_INV_agregar_carrera;
    private javax.swing.JComboBox<String> jcb_VER_PROY_agregar_carrera;
    private javax.swing.JComboBox<String> jcb_VER_PUB_agregar_proyecto;
    private javax.swing.JDialog jd_carreras;
    private javax.swing.JDialog jd_investigadores;
    private javax.swing.JDialog jd_proyectos;
    private javax.swing.JDialog jd_publicaciones;
    private javax.swing.JMenu jm_FILE;
    private javax.swing.JMenu jm_VER;
    private javax.swing.JMenuItem jmi_FILE_abrir;
    private javax.swing.JMenuItem jmi_FILE_close;
    private javax.swing.JMenuItem jmi_FILE_exit;
    private javax.swing.JMenuItem jmi_FILE_guardar;
    private javax.swing.JMenuItem jmi_VER_carreras;
    private javax.swing.JMenuItem jmi_VER_investigadores;
    private javax.swing.JMenuItem jmi_VER_proyectos;
    private javax.swing.JMenuItem jmi_VER_publicaciones;
    private javax.swing.JTable jtbl_CARRERA_buscar;
    private javax.swing.JTable jtbl_CARRERA_listar;
    private javax.swing.JTable jtbl_INVT_borrar;
    private javax.swing.JTable jtbl_INVT_listar;
    private javax.swing.JTable jtbl_PROY_buscar;
    private javax.swing.JTable jtbl_PROY_ver;
    private javax.swing.JTable jtbl_PUB_buscar;
    private javax.swing.JTable jtbl_PUB_listar;
    private javax.swing.JTabbedPane jtp_VER_investigadores;
    private javax.swing.JTabbedPane jtp_VER_proyectos;
    private javax.swing.JTabbedPane jtp_carreras;
    private javax.swing.JTabbedPane jtp_publicaciones;
    private javax.swing.JRadioButton rbt_CARRERA_agregar_activo;
    private javax.swing.JRadioButton rbt_CARRERA_agregar_inactivo;
    private javax.swing.JRadioButton rbt_VER_INV_agregar_activo;
    private javax.swing.JRadioButton rbt_VER_INV_agregar_inactivo;
    private javax.swing.JRadioButton rbt_VER_PROY_agregar_enviado;
    private javax.swing.JRadioButton rbt_VER_PROY_agregar_iniciado;
    private javax.swing.JRadioButton rbt_VER_PROY_agregar_publicado;
    private javax.swing.JRadioButton rbt_VER_PROY_agregar_rechazado;
    private javax.swing.JRadioButton rbt_VER_PUB_agregar_publicacion;
    private javax.swing.JRadioButton rbt_VER_PUB_agregar_revista;
    private javax.swing.JTextField tf_CARRERA_agregar_codigo;
    private javax.swing.JTextField tf_CARRERA_agregar_nombre;
    private javax.swing.JTextField tf_CARRERA_buscar;
    private javax.swing.JTextField tf_VER_INV_agregar_codigo;
    private javax.swing.JTextField tf_VER_INV_agregar_nombre;
    private javax.swing.JTextField tf_VER_PROY_agregar_codigo;
    private javax.swing.JTextField tf_VER_PROY_agregar_tema;
    private javax.swing.JTextField tf_VER_PUB_agregar_codigo;
    // End of variables declaration//GEN-END:variables

    Carrera car;
    int pos;
}